name: infra-orchestrator
version: '3.8'
services:
  devcontainer:
    container_name: infra-orchestrator
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
