name: Run Terraform Command

on:
  workflow_dispatch:
    inputs:
      terraform_command:
        description: "Terraform command to run (e.g. plan, apply, destroy)"
        required: true
        default: "apply"

jobs:
  terraform:
    name: Run Terraform ${{ github.event.inputs.terraform_command }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Run Terraform Command
        working-directory: ./terraform
        run: terraform ${{ github.event.inputs.terraform_command }} -auto-approve
